version: "3.5"
services:
  app:
    image: nanoninja/php-fpm
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - default
    depends_on:
      - mysql
    entrypoint: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=80"]

  mysql:
    image: mysql:5.7
    environment:
      - "MYSQL_DATABASE=blog"
      - "MYSQL_USER=blog"
      - "MYSQL_PASSWORD=blog"
      - "MYSQL_ROOT_PASSWORD=blog"
    networks:
      - default

networks:
  default:
    driver: bridge
